package com.example.demo.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
public class StudyCallRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_call_record.call_record_id
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    private Integer callRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_call_record.call_id
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    private String callId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_call_record.kfext
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    private String kfext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_call_record.call_mobile
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    private String callMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_call_record.call_time
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    private Long callTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_call_record.delete_flag
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_call_record.call_record_id
     *
     * @return the value of study_call_record.call_record_id
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public Integer getCallRecordId() {
        return callRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_call_record.call_record_id
     *
     * @param callRecordId the value for study_call_record.call_record_id
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public void setCallRecordId(Integer callRecordId) {
        this.callRecordId = callRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_call_record.call_id
     *
     * @return the value of study_call_record.call_id
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public String getCallId() {
        return callId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_call_record.call_id
     *
     * @param callId the value for study_call_record.call_id
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public void setCallId(String callId) {
        this.callId = callId == null ? null : callId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_call_record.kfext
     *
     * @return the value of study_call_record.kfext
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public String getKfext() {
        return kfext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_call_record.kfext
     *
     * @param kfext the value for study_call_record.kfext
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public void setKfext(String kfext) {
        this.kfext = kfext == null ? null : kfext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_call_record.call_mobile
     *
     * @return the value of study_call_record.call_mobile
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public String getCallMobile() {
        return callMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_call_record.call_mobile
     *
     * @param callMobile the value for study_call_record.call_mobile
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public void setCallMobile(String callMobile) {
        this.callMobile = callMobile == null ? null : callMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_call_record.call_time
     *
     * @return the value of study_call_record.call_time
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public Long getCallTime() {
        return callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_call_record.call_time
     *
     * @param callTime the value for study_call_record.call_time
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public void setCallTime(Long callTime) {
        this.callTime = callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_call_record.delete_flag
     *
     * @return the value of study_call_record.delete_flag
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_call_record.delete_flag
     *
     * @param deleteFlag the value for study_call_record.delete_flag
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StudyCallRecord other = (StudyCallRecord) that;
        return (this.getCallRecordId() == null ? other.getCallRecordId() == null : this.getCallRecordId().equals(other.getCallRecordId()))
            && (this.getCallId() == null ? other.getCallId() == null : this.getCallId().equals(other.getCallId()))
            && (this.getKfext() == null ? other.getKfext() == null : this.getKfext().equals(other.getKfext()))
            && (this.getCallMobile() == null ? other.getCallMobile() == null : this.getCallMobile().equals(other.getCallMobile()))
            && (this.getCallTime() == null ? other.getCallTime() == null : this.getCallTime().equals(other.getCallTime()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCallRecordId() == null) ? 0 : getCallRecordId().hashCode());
        result = prime * result + ((getCallId() == null) ? 0 : getCallId().hashCode());
        result = prime * result + ((getKfext() == null) ? 0 : getKfext().hashCode());
        result = prime * result + ((getCallMobile() == null) ? 0 : getCallMobile().hashCode());
        result = prime * result + ((getCallTime() == null) ? 0 : getCallTime().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", callRecordId=").append(callRecordId);
        sb.append(", callId=").append(callId);
        sb.append(", kfext=").append(kfext);
        sb.append(", callMobile=").append(callMobile);
        sb.append(", callTime=").append(callTime);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}