package com.example.demo.model;

import java.util.ArrayList;
import java.util.List;

public class StudyCallRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public StudyCallRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCallRecordIdIsNull() {
            addCriterion("call_record_id is null");
            return (Criteria) this;
        }

        public Criteria andCallRecordIdIsNotNull() {
            addCriterion("call_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andCallRecordIdEqualTo(Integer value) {
            addCriterion("call_record_id =", value, "callRecordId");
            return (Criteria) this;
        }

        public Criteria andCallRecordIdNotEqualTo(Integer value) {
            addCriterion("call_record_id <>", value, "callRecordId");
            return (Criteria) this;
        }

        public Criteria andCallRecordIdGreaterThan(Integer value) {
            addCriterion("call_record_id >", value, "callRecordId");
            return (Criteria) this;
        }

        public Criteria andCallRecordIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("call_record_id >=", value, "callRecordId");
            return (Criteria) this;
        }

        public Criteria andCallRecordIdLessThan(Integer value) {
            addCriterion("call_record_id <", value, "callRecordId");
            return (Criteria) this;
        }

        public Criteria andCallRecordIdLessThanOrEqualTo(Integer value) {
            addCriterion("call_record_id <=", value, "callRecordId");
            return (Criteria) this;
        }

        public Criteria andCallRecordIdIn(List<Integer> values) {
            addCriterion("call_record_id in", values, "callRecordId");
            return (Criteria) this;
        }

        public Criteria andCallRecordIdNotIn(List<Integer> values) {
            addCriterion("call_record_id not in", values, "callRecordId");
            return (Criteria) this;
        }

        public Criteria andCallRecordIdBetween(Integer value1, Integer value2) {
            addCriterion("call_record_id between", value1, value2, "callRecordId");
            return (Criteria) this;
        }

        public Criteria andCallRecordIdNotBetween(Integer value1, Integer value2) {
            addCriterion("call_record_id not between", value1, value2, "callRecordId");
            return (Criteria) this;
        }

        public Criteria andCallIdIsNull() {
            addCriterion("call_id is null");
            return (Criteria) this;
        }

        public Criteria andCallIdIsNotNull() {
            addCriterion("call_id is not null");
            return (Criteria) this;
        }

        public Criteria andCallIdEqualTo(String value) {
            addCriterion("call_id =", value, "callId");
            return (Criteria) this;
        }

        public Criteria andCallIdNotEqualTo(String value) {
            addCriterion("call_id <>", value, "callId");
            return (Criteria) this;
        }

        public Criteria andCallIdGreaterThan(String value) {
            addCriterion("call_id >", value, "callId");
            return (Criteria) this;
        }

        public Criteria andCallIdGreaterThanOrEqualTo(String value) {
            addCriterion("call_id >=", value, "callId");
            return (Criteria) this;
        }

        public Criteria andCallIdLessThan(String value) {
            addCriterion("call_id <", value, "callId");
            return (Criteria) this;
        }

        public Criteria andCallIdLessThanOrEqualTo(String value) {
            addCriterion("call_id <=", value, "callId");
            return (Criteria) this;
        }

        public Criteria andCallIdLike(String value) {
            addCriterion("call_id like", value, "callId");
            return (Criteria) this;
        }

        public Criteria andCallIdNotLike(String value) {
            addCriterion("call_id not like", value, "callId");
            return (Criteria) this;
        }

        public Criteria andCallIdIn(List<String> values) {
            addCriterion("call_id in", values, "callId");
            return (Criteria) this;
        }

        public Criteria andCallIdNotIn(List<String> values) {
            addCriterion("call_id not in", values, "callId");
            return (Criteria) this;
        }

        public Criteria andCallIdBetween(String value1, String value2) {
            addCriterion("call_id between", value1, value2, "callId");
            return (Criteria) this;
        }

        public Criteria andCallIdNotBetween(String value1, String value2) {
            addCriterion("call_id not between", value1, value2, "callId");
            return (Criteria) this;
        }

        public Criteria andKfextIsNull() {
            addCriterion("kfext is null");
            return (Criteria) this;
        }

        public Criteria andKfextIsNotNull() {
            addCriterion("kfext is not null");
            return (Criteria) this;
        }

        public Criteria andKfextEqualTo(String value) {
            addCriterion("kfext =", value, "kfext");
            return (Criteria) this;
        }

        public Criteria andKfextNotEqualTo(String value) {
            addCriterion("kfext <>", value, "kfext");
            return (Criteria) this;
        }

        public Criteria andKfextGreaterThan(String value) {
            addCriterion("kfext >", value, "kfext");
            return (Criteria) this;
        }

        public Criteria andKfextGreaterThanOrEqualTo(String value) {
            addCriterion("kfext >=", value, "kfext");
            return (Criteria) this;
        }

        public Criteria andKfextLessThan(String value) {
            addCriterion("kfext <", value, "kfext");
            return (Criteria) this;
        }

        public Criteria andKfextLessThanOrEqualTo(String value) {
            addCriterion("kfext <=", value, "kfext");
            return (Criteria) this;
        }

        public Criteria andKfextLike(String value) {
            addCriterion("kfext like", value, "kfext");
            return (Criteria) this;
        }

        public Criteria andKfextNotLike(String value) {
            addCriterion("kfext not like", value, "kfext");
            return (Criteria) this;
        }

        public Criteria andKfextIn(List<String> values) {
            addCriterion("kfext in", values, "kfext");
            return (Criteria) this;
        }

        public Criteria andKfextNotIn(List<String> values) {
            addCriterion("kfext not in", values, "kfext");
            return (Criteria) this;
        }

        public Criteria andKfextBetween(String value1, String value2) {
            addCriterion("kfext between", value1, value2, "kfext");
            return (Criteria) this;
        }

        public Criteria andKfextNotBetween(String value1, String value2) {
            addCriterion("kfext not between", value1, value2, "kfext");
            return (Criteria) this;
        }

        public Criteria andCallMobileIsNull() {
            addCriterion("call_mobile is null");
            return (Criteria) this;
        }

        public Criteria andCallMobileIsNotNull() {
            addCriterion("call_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andCallMobileEqualTo(String value) {
            addCriterion("call_mobile =", value, "callMobile");
            return (Criteria) this;
        }

        public Criteria andCallMobileNotEqualTo(String value) {
            addCriterion("call_mobile <>", value, "callMobile");
            return (Criteria) this;
        }

        public Criteria andCallMobileGreaterThan(String value) {
            addCriterion("call_mobile >", value, "callMobile");
            return (Criteria) this;
        }

        public Criteria andCallMobileGreaterThanOrEqualTo(String value) {
            addCriterion("call_mobile >=", value, "callMobile");
            return (Criteria) this;
        }

        public Criteria andCallMobileLessThan(String value) {
            addCriterion("call_mobile <", value, "callMobile");
            return (Criteria) this;
        }

        public Criteria andCallMobileLessThanOrEqualTo(String value) {
            addCriterion("call_mobile <=", value, "callMobile");
            return (Criteria) this;
        }

        public Criteria andCallMobileLike(String value) {
            addCriterion("call_mobile like", value, "callMobile");
            return (Criteria) this;
        }

        public Criteria andCallMobileNotLike(String value) {
            addCriterion("call_mobile not like", value, "callMobile");
            return (Criteria) this;
        }

        public Criteria andCallMobileIn(List<String> values) {
            addCriterion("call_mobile in", values, "callMobile");
            return (Criteria) this;
        }

        public Criteria andCallMobileNotIn(List<String> values) {
            addCriterion("call_mobile not in", values, "callMobile");
            return (Criteria) this;
        }

        public Criteria andCallMobileBetween(String value1, String value2) {
            addCriterion("call_mobile between", value1, value2, "callMobile");
            return (Criteria) this;
        }

        public Criteria andCallMobileNotBetween(String value1, String value2) {
            addCriterion("call_mobile not between", value1, value2, "callMobile");
            return (Criteria) this;
        }

        public Criteria andCallTimeIsNull() {
            addCriterion("call_time is null");
            return (Criteria) this;
        }

        public Criteria andCallTimeIsNotNull() {
            addCriterion("call_time is not null");
            return (Criteria) this;
        }

        public Criteria andCallTimeEqualTo(Long value) {
            addCriterion("call_time =", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeNotEqualTo(Long value) {
            addCriterion("call_time <>", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeGreaterThan(Long value) {
            addCriterion("call_time >", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("call_time >=", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeLessThan(Long value) {
            addCriterion("call_time <", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeLessThanOrEqualTo(Long value) {
            addCriterion("call_time <=", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeIn(List<Long> values) {
            addCriterion("call_time in", values, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeNotIn(List<Long> values) {
            addCriterion("call_time not in", values, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeBetween(Long value1, Long value2) {
            addCriterion("call_time between", value1, value2, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeNotBetween(Long value1, Long value2) {
            addCriterion("call_time not between", value1, value2, "callTime");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Integer value) {
            addCriterion("delete_flag =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Integer value) {
            addCriterion("delete_flag <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Integer value) {
            addCriterion("delete_flag >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("delete_flag >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Integer value) {
            addCriterion("delete_flag <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Integer value) {
            addCriterion("delete_flag <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Integer> values) {
            addCriterion("delete_flag in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Integer> values) {
            addCriterion("delete_flag not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Integer value1, Integer value2) {
            addCriterion("delete_flag between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("delete_flag not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table study_call_record
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 15 22:59:40 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}