package com.example.demo.model;

import java.util.ArrayList;
import java.util.List;

public class WaysMallExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public WaysMallExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMallIdIsNull() {
            addCriterion("mall_id is null");
            return (Criteria) this;
        }

        public Criteria andMallIdIsNotNull() {
            addCriterion("mall_id is not null");
            return (Criteria) this;
        }

        public Criteria andMallIdEqualTo(Integer value) {
            addCriterion("mall_id =", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdNotEqualTo(Integer value) {
            addCriterion("mall_id <>", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdGreaterThan(Integer value) {
            addCriterion("mall_id >", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mall_id >=", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdLessThan(Integer value) {
            addCriterion("mall_id <", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdLessThanOrEqualTo(Integer value) {
            addCriterion("mall_id <=", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdIn(List<Integer> values) {
            addCriterion("mall_id in", values, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdNotIn(List<Integer> values) {
            addCriterion("mall_id not in", values, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdBetween(Integer value1, Integer value2) {
            addCriterion("mall_id between", value1, value2, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mall_id not between", value1, value2, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallCodeIsNull() {
            addCriterion("mall_code is null");
            return (Criteria) this;
        }

        public Criteria andMallCodeIsNotNull() {
            addCriterion("mall_code is not null");
            return (Criteria) this;
        }

        public Criteria andMallCodeEqualTo(String value) {
            addCriterion("mall_code =", value, "mallCode");
            return (Criteria) this;
        }

        public Criteria andMallCodeNotEqualTo(String value) {
            addCriterion("mall_code <>", value, "mallCode");
            return (Criteria) this;
        }

        public Criteria andMallCodeGreaterThan(String value) {
            addCriterion("mall_code >", value, "mallCode");
            return (Criteria) this;
        }

        public Criteria andMallCodeGreaterThanOrEqualTo(String value) {
            addCriterion("mall_code >=", value, "mallCode");
            return (Criteria) this;
        }

        public Criteria andMallCodeLessThan(String value) {
            addCriterion("mall_code <", value, "mallCode");
            return (Criteria) this;
        }

        public Criteria andMallCodeLessThanOrEqualTo(String value) {
            addCriterion("mall_code <=", value, "mallCode");
            return (Criteria) this;
        }

        public Criteria andMallCodeLike(String value) {
            addCriterion("mall_code like", value, "mallCode");
            return (Criteria) this;
        }

        public Criteria andMallCodeNotLike(String value) {
            addCriterion("mall_code not like", value, "mallCode");
            return (Criteria) this;
        }

        public Criteria andMallCodeIn(List<String> values) {
            addCriterion("mall_code in", values, "mallCode");
            return (Criteria) this;
        }

        public Criteria andMallCodeNotIn(List<String> values) {
            addCriterion("mall_code not in", values, "mallCode");
            return (Criteria) this;
        }

        public Criteria andMallCodeBetween(String value1, String value2) {
            addCriterion("mall_code between", value1, value2, "mallCode");
            return (Criteria) this;
        }

        public Criteria andMallCodeNotBetween(String value1, String value2) {
            addCriterion("mall_code not between", value1, value2, "mallCode");
            return (Criteria) this;
        }

        public Criteria andMallNameIsNull() {
            addCriterion("mall_name is null");
            return (Criteria) this;
        }

        public Criteria andMallNameIsNotNull() {
            addCriterion("mall_name is not null");
            return (Criteria) this;
        }

        public Criteria andMallNameEqualTo(String value) {
            addCriterion("mall_name =", value, "mallName");
            return (Criteria) this;
        }

        public Criteria andMallNameNotEqualTo(String value) {
            addCriterion("mall_name <>", value, "mallName");
            return (Criteria) this;
        }

        public Criteria andMallNameGreaterThan(String value) {
            addCriterion("mall_name >", value, "mallName");
            return (Criteria) this;
        }

        public Criteria andMallNameGreaterThanOrEqualTo(String value) {
            addCriterion("mall_name >=", value, "mallName");
            return (Criteria) this;
        }

        public Criteria andMallNameLessThan(String value) {
            addCriterion("mall_name <", value, "mallName");
            return (Criteria) this;
        }

        public Criteria andMallNameLessThanOrEqualTo(String value) {
            addCriterion("mall_name <=", value, "mallName");
            return (Criteria) this;
        }

        public Criteria andMallNameLike(String value) {
            addCriterion("mall_name like", value, "mallName");
            return (Criteria) this;
        }

        public Criteria andMallNameNotLike(String value) {
            addCriterion("mall_name not like", value, "mallName");
            return (Criteria) this;
        }

        public Criteria andMallNameIn(List<String> values) {
            addCriterion("mall_name in", values, "mallName");
            return (Criteria) this;
        }

        public Criteria andMallNameNotIn(List<String> values) {
            addCriterion("mall_name not in", values, "mallName");
            return (Criteria) this;
        }

        public Criteria andMallNameBetween(String value1, String value2) {
            addCriterion("mall_name between", value1, value2, "mallName");
            return (Criteria) this;
        }

        public Criteria andMallNameNotBetween(String value1, String value2) {
            addCriterion("mall_name not between", value1, value2, "mallName");
            return (Criteria) this;
        }

        public Criteria andMallNameEngIsNull() {
            addCriterion("mall_name_eng is null");
            return (Criteria) this;
        }

        public Criteria andMallNameEngIsNotNull() {
            addCriterion("mall_name_eng is not null");
            return (Criteria) this;
        }

        public Criteria andMallNameEngEqualTo(String value) {
            addCriterion("mall_name_eng =", value, "mallNameEng");
            return (Criteria) this;
        }

        public Criteria andMallNameEngNotEqualTo(String value) {
            addCriterion("mall_name_eng <>", value, "mallNameEng");
            return (Criteria) this;
        }

        public Criteria andMallNameEngGreaterThan(String value) {
            addCriterion("mall_name_eng >", value, "mallNameEng");
            return (Criteria) this;
        }

        public Criteria andMallNameEngGreaterThanOrEqualTo(String value) {
            addCriterion("mall_name_eng >=", value, "mallNameEng");
            return (Criteria) this;
        }

        public Criteria andMallNameEngLessThan(String value) {
            addCriterion("mall_name_eng <", value, "mallNameEng");
            return (Criteria) this;
        }

        public Criteria andMallNameEngLessThanOrEqualTo(String value) {
            addCriterion("mall_name_eng <=", value, "mallNameEng");
            return (Criteria) this;
        }

        public Criteria andMallNameEngLike(String value) {
            addCriterion("mall_name_eng like", value, "mallNameEng");
            return (Criteria) this;
        }

        public Criteria andMallNameEngNotLike(String value) {
            addCriterion("mall_name_eng not like", value, "mallNameEng");
            return (Criteria) this;
        }

        public Criteria andMallNameEngIn(List<String> values) {
            addCriterion("mall_name_eng in", values, "mallNameEng");
            return (Criteria) this;
        }

        public Criteria andMallNameEngNotIn(List<String> values) {
            addCriterion("mall_name_eng not in", values, "mallNameEng");
            return (Criteria) this;
        }

        public Criteria andMallNameEngBetween(String value1, String value2) {
            addCriterion("mall_name_eng between", value1, value2, "mallNameEng");
            return (Criteria) this;
        }

        public Criteria andMallNameEngNotBetween(String value1, String value2) {
            addCriterion("mall_name_eng not between", value1, value2, "mallNameEng");
            return (Criteria) this;
        }

        public Criteria andMallAliasIsNull() {
            addCriterion("mall_alias is null");
            return (Criteria) this;
        }

        public Criteria andMallAliasIsNotNull() {
            addCriterion("mall_alias is not null");
            return (Criteria) this;
        }

        public Criteria andMallAliasEqualTo(String value) {
            addCriterion("mall_alias =", value, "mallAlias");
            return (Criteria) this;
        }

        public Criteria andMallAliasNotEqualTo(String value) {
            addCriterion("mall_alias <>", value, "mallAlias");
            return (Criteria) this;
        }

        public Criteria andMallAliasGreaterThan(String value) {
            addCriterion("mall_alias >", value, "mallAlias");
            return (Criteria) this;
        }

        public Criteria andMallAliasGreaterThanOrEqualTo(String value) {
            addCriterion("mall_alias >=", value, "mallAlias");
            return (Criteria) this;
        }

        public Criteria andMallAliasLessThan(String value) {
            addCriterion("mall_alias <", value, "mallAlias");
            return (Criteria) this;
        }

        public Criteria andMallAliasLessThanOrEqualTo(String value) {
            addCriterion("mall_alias <=", value, "mallAlias");
            return (Criteria) this;
        }

        public Criteria andMallAliasLike(String value) {
            addCriterion("mall_alias like", value, "mallAlias");
            return (Criteria) this;
        }

        public Criteria andMallAliasNotLike(String value) {
            addCriterion("mall_alias not like", value, "mallAlias");
            return (Criteria) this;
        }

        public Criteria andMallAliasIn(List<String> values) {
            addCriterion("mall_alias in", values, "mallAlias");
            return (Criteria) this;
        }

        public Criteria andMallAliasNotIn(List<String> values) {
            addCriterion("mall_alias not in", values, "mallAlias");
            return (Criteria) this;
        }

        public Criteria andMallAliasBetween(String value1, String value2) {
            addCriterion("mall_alias between", value1, value2, "mallAlias");
            return (Criteria) this;
        }

        public Criteria andMallAliasNotBetween(String value1, String value2) {
            addCriterion("mall_alias not between", value1, value2, "mallAlias");
            return (Criteria) this;
        }

        public Criteria andLogoIsNull() {
            addCriterion("logo is null");
            return (Criteria) this;
        }

        public Criteria andLogoIsNotNull() {
            addCriterion("logo is not null");
            return (Criteria) this;
        }

        public Criteria andLogoEqualTo(String value) {
            addCriterion("logo =", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotEqualTo(String value) {
            addCriterion("logo <>", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThan(String value) {
            addCriterion("logo >", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThanOrEqualTo(String value) {
            addCriterion("logo >=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThan(String value) {
            addCriterion("logo <", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThanOrEqualTo(String value) {
            addCriterion("logo <=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLike(String value) {
            addCriterion("logo like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotLike(String value) {
            addCriterion("logo not like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoIn(List<String> values) {
            addCriterion("logo in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotIn(List<String> values) {
            addCriterion("logo not in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoBetween(String value1, String value2) {
            addCriterion("logo between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotBetween(String value1, String value2) {
            addCriterion("logo not between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andIsUseIsNull() {
            addCriterion("is_use is null");
            return (Criteria) this;
        }

        public Criteria andIsUseIsNotNull() {
            addCriterion("is_use is not null");
            return (Criteria) this;
        }

        public Criteria andIsUseEqualTo(Short value) {
            addCriterion("is_use =", value, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseNotEqualTo(Short value) {
            addCriterion("is_use <>", value, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseGreaterThan(Short value) {
            addCriterion("is_use >", value, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseGreaterThanOrEqualTo(Short value) {
            addCriterion("is_use >=", value, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseLessThan(Short value) {
            addCriterion("is_use <", value, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseLessThanOrEqualTo(Short value) {
            addCriterion("is_use <=", value, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseIn(List<Short> values) {
            addCriterion("is_use in", values, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseNotIn(List<Short> values) {
            addCriterion("is_use not in", values, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseBetween(Short value1, Short value2) {
            addCriterion("is_use between", value1, value2, "isUse");
            return (Criteria) this;
        }

        public Criteria andIsUseNotBetween(Short value1, Short value2) {
            addCriterion("is_use not between", value1, value2, "isUse");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(Integer value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(Integer value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(Integer value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(Integer value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(Integer value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<Integer> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<Integer> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(Integer value1, Integer value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(Integer value1, Integer value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Integer value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Integer value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Integer> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(Integer value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(Integer value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(Integer value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(Integer value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(Integer value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<Integer> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<Integer> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(Integer value1, Integer value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(Integer value1, Integer value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Integer value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Integer value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Integer value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Integer value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Integer> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Integer> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeSeparatorIsNull() {
            addCriterion("place_code_separator is null");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeSeparatorIsNotNull() {
            addCriterion("place_code_separator is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeSeparatorEqualTo(String value) {
            addCriterion("place_code_separator =", value, "placeCodeSeparator");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeSeparatorNotEqualTo(String value) {
            addCriterion("place_code_separator <>", value, "placeCodeSeparator");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeSeparatorGreaterThan(String value) {
            addCriterion("place_code_separator >", value, "placeCodeSeparator");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeSeparatorGreaterThanOrEqualTo(String value) {
            addCriterion("place_code_separator >=", value, "placeCodeSeparator");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeSeparatorLessThan(String value) {
            addCriterion("place_code_separator <", value, "placeCodeSeparator");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeSeparatorLessThanOrEqualTo(String value) {
            addCriterion("place_code_separator <=", value, "placeCodeSeparator");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeSeparatorLike(String value) {
            addCriterion("place_code_separator like", value, "placeCodeSeparator");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeSeparatorNotLike(String value) {
            addCriterion("place_code_separator not like", value, "placeCodeSeparator");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeSeparatorIn(List<String> values) {
            addCriterion("place_code_separator in", values, "placeCodeSeparator");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeSeparatorNotIn(List<String> values) {
            addCriterion("place_code_separator not in", values, "placeCodeSeparator");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeSeparatorBetween(String value1, String value2) {
            addCriterion("place_code_separator between", value1, value2, "placeCodeSeparator");
            return (Criteria) this;
        }

        public Criteria andPlaceCodeSeparatorNotBetween(String value1, String value2) {
            addCriterion("place_code_separator not between", value1, value2, "placeCodeSeparator");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andStatusOfMicroMallIsNull() {
            addCriterion("status_of_micro_mall is null");
            return (Criteria) this;
        }

        public Criteria andStatusOfMicroMallIsNotNull() {
            addCriterion("status_of_micro_mall is not null");
            return (Criteria) this;
        }

        public Criteria andStatusOfMicroMallEqualTo(String value) {
            addCriterion("status_of_micro_mall =", value, "statusOfMicroMall");
            return (Criteria) this;
        }

        public Criteria andStatusOfMicroMallNotEqualTo(String value) {
            addCriterion("status_of_micro_mall <>", value, "statusOfMicroMall");
            return (Criteria) this;
        }

        public Criteria andStatusOfMicroMallGreaterThan(String value) {
            addCriterion("status_of_micro_mall >", value, "statusOfMicroMall");
            return (Criteria) this;
        }

        public Criteria andStatusOfMicroMallGreaterThanOrEqualTo(String value) {
            addCriterion("status_of_micro_mall >=", value, "statusOfMicroMall");
            return (Criteria) this;
        }

        public Criteria andStatusOfMicroMallLessThan(String value) {
            addCriterion("status_of_micro_mall <", value, "statusOfMicroMall");
            return (Criteria) this;
        }

        public Criteria andStatusOfMicroMallLessThanOrEqualTo(String value) {
            addCriterion("status_of_micro_mall <=", value, "statusOfMicroMall");
            return (Criteria) this;
        }

        public Criteria andStatusOfMicroMallLike(String value) {
            addCriterion("status_of_micro_mall like", value, "statusOfMicroMall");
            return (Criteria) this;
        }

        public Criteria andStatusOfMicroMallNotLike(String value) {
            addCriterion("status_of_micro_mall not like", value, "statusOfMicroMall");
            return (Criteria) this;
        }

        public Criteria andStatusOfMicroMallIn(List<String> values) {
            addCriterion("status_of_micro_mall in", values, "statusOfMicroMall");
            return (Criteria) this;
        }

        public Criteria andStatusOfMicroMallNotIn(List<String> values) {
            addCriterion("status_of_micro_mall not in", values, "statusOfMicroMall");
            return (Criteria) this;
        }

        public Criteria andStatusOfMicroMallBetween(String value1, String value2) {
            addCriterion("status_of_micro_mall between", value1, value2, "statusOfMicroMall");
            return (Criteria) this;
        }

        public Criteria andStatusOfMicroMallNotBetween(String value1, String value2) {
            addCriterion("status_of_micro_mall not between", value1, value2, "statusOfMicroMall");
            return (Criteria) this;
        }

        public Criteria andWechatPublicAccountIsNull() {
            addCriterion("wechat_public_account is null");
            return (Criteria) this;
        }

        public Criteria andWechatPublicAccountIsNotNull() {
            addCriterion("wechat_public_account is not null");
            return (Criteria) this;
        }

        public Criteria andWechatPublicAccountEqualTo(String value) {
            addCriterion("wechat_public_account =", value, "wechatPublicAccount");
            return (Criteria) this;
        }

        public Criteria andWechatPublicAccountNotEqualTo(String value) {
            addCriterion("wechat_public_account <>", value, "wechatPublicAccount");
            return (Criteria) this;
        }

        public Criteria andWechatPublicAccountGreaterThan(String value) {
            addCriterion("wechat_public_account >", value, "wechatPublicAccount");
            return (Criteria) this;
        }

        public Criteria andWechatPublicAccountGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_public_account >=", value, "wechatPublicAccount");
            return (Criteria) this;
        }

        public Criteria andWechatPublicAccountLessThan(String value) {
            addCriterion("wechat_public_account <", value, "wechatPublicAccount");
            return (Criteria) this;
        }

        public Criteria andWechatPublicAccountLessThanOrEqualTo(String value) {
            addCriterion("wechat_public_account <=", value, "wechatPublicAccount");
            return (Criteria) this;
        }

        public Criteria andWechatPublicAccountLike(String value) {
            addCriterion("wechat_public_account like", value, "wechatPublicAccount");
            return (Criteria) this;
        }

        public Criteria andWechatPublicAccountNotLike(String value) {
            addCriterion("wechat_public_account not like", value, "wechatPublicAccount");
            return (Criteria) this;
        }

        public Criteria andWechatPublicAccountIn(List<String> values) {
            addCriterion("wechat_public_account in", values, "wechatPublicAccount");
            return (Criteria) this;
        }

        public Criteria andWechatPublicAccountNotIn(List<String> values) {
            addCriterion("wechat_public_account not in", values, "wechatPublicAccount");
            return (Criteria) this;
        }

        public Criteria andWechatPublicAccountBetween(String value1, String value2) {
            addCriterion("wechat_public_account between", value1, value2, "wechatPublicAccount");
            return (Criteria) this;
        }

        public Criteria andWechatPublicAccountNotBetween(String value1, String value2) {
            addCriterion("wechat_public_account not between", value1, value2, "wechatPublicAccount");
            return (Criteria) this;
        }

        public Criteria andTelphoneIsNull() {
            addCriterion("telphone is null");
            return (Criteria) this;
        }

        public Criteria andTelphoneIsNotNull() {
            addCriterion("telphone is not null");
            return (Criteria) this;
        }

        public Criteria andTelphoneEqualTo(String value) {
            addCriterion("telphone =", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotEqualTo(String value) {
            addCriterion("telphone <>", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneGreaterThan(String value) {
            addCriterion("telphone >", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneGreaterThanOrEqualTo(String value) {
            addCriterion("telphone >=", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLessThan(String value) {
            addCriterion("telphone <", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLessThanOrEqualTo(String value) {
            addCriterion("telphone <=", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLike(String value) {
            addCriterion("telphone like", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotLike(String value) {
            addCriterion("telphone not like", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneIn(List<String> values) {
            addCriterion("telphone in", values, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotIn(List<String> values) {
            addCriterion("telphone not in", values, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneBetween(String value1, String value2) {
            addCriterion("telphone between", value1, value2, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotBetween(String value1, String value2) {
            addCriterion("telphone not between", value1, value2, "telphone");
            return (Criteria) this;
        }

        public Criteria andMallTypeIsNull() {
            addCriterion("mall_type is null");
            return (Criteria) this;
        }

        public Criteria andMallTypeIsNotNull() {
            addCriterion("mall_type is not null");
            return (Criteria) this;
        }

        public Criteria andMallTypeEqualTo(String value) {
            addCriterion("mall_type =", value, "mallType");
            return (Criteria) this;
        }

        public Criteria andMallTypeNotEqualTo(String value) {
            addCriterion("mall_type <>", value, "mallType");
            return (Criteria) this;
        }

        public Criteria andMallTypeGreaterThan(String value) {
            addCriterion("mall_type >", value, "mallType");
            return (Criteria) this;
        }

        public Criteria andMallTypeGreaterThanOrEqualTo(String value) {
            addCriterion("mall_type >=", value, "mallType");
            return (Criteria) this;
        }

        public Criteria andMallTypeLessThan(String value) {
            addCriterion("mall_type <", value, "mallType");
            return (Criteria) this;
        }

        public Criteria andMallTypeLessThanOrEqualTo(String value) {
            addCriterion("mall_type <=", value, "mallType");
            return (Criteria) this;
        }

        public Criteria andMallTypeLike(String value) {
            addCriterion("mall_type like", value, "mallType");
            return (Criteria) this;
        }

        public Criteria andMallTypeNotLike(String value) {
            addCriterion("mall_type not like", value, "mallType");
            return (Criteria) this;
        }

        public Criteria andMallTypeIn(List<String> values) {
            addCriterion("mall_type in", values, "mallType");
            return (Criteria) this;
        }

        public Criteria andMallTypeNotIn(List<String> values) {
            addCriterion("mall_type not in", values, "mallType");
            return (Criteria) this;
        }

        public Criteria andMallTypeBetween(String value1, String value2) {
            addCriterion("mall_type between", value1, value2, "mallType");
            return (Criteria) this;
        }

        public Criteria andMallTypeNotBetween(String value1, String value2) {
            addCriterion("mall_type not between", value1, value2, "mallType");
            return (Criteria) this;
        }

        public Criteria andMallEnvIsNull() {
            addCriterion("mall_env is null");
            return (Criteria) this;
        }

        public Criteria andMallEnvIsNotNull() {
            addCriterion("mall_env is not null");
            return (Criteria) this;
        }

        public Criteria andMallEnvEqualTo(String value) {
            addCriterion("mall_env =", value, "mallEnv");
            return (Criteria) this;
        }

        public Criteria andMallEnvNotEqualTo(String value) {
            addCriterion("mall_env <>", value, "mallEnv");
            return (Criteria) this;
        }

        public Criteria andMallEnvGreaterThan(String value) {
            addCriterion("mall_env >", value, "mallEnv");
            return (Criteria) this;
        }

        public Criteria andMallEnvGreaterThanOrEqualTo(String value) {
            addCriterion("mall_env >=", value, "mallEnv");
            return (Criteria) this;
        }

        public Criteria andMallEnvLessThan(String value) {
            addCriterion("mall_env <", value, "mallEnv");
            return (Criteria) this;
        }

        public Criteria andMallEnvLessThanOrEqualTo(String value) {
            addCriterion("mall_env <=", value, "mallEnv");
            return (Criteria) this;
        }

        public Criteria andMallEnvLike(String value) {
            addCriterion("mall_env like", value, "mallEnv");
            return (Criteria) this;
        }

        public Criteria andMallEnvNotLike(String value) {
            addCriterion("mall_env not like", value, "mallEnv");
            return (Criteria) this;
        }

        public Criteria andMallEnvIn(List<String> values) {
            addCriterion("mall_env in", values, "mallEnv");
            return (Criteria) this;
        }

        public Criteria andMallEnvNotIn(List<String> values) {
            addCriterion("mall_env not in", values, "mallEnv");
            return (Criteria) this;
        }

        public Criteria andMallEnvBetween(String value1, String value2) {
            addCriterion("mall_env between", value1, value2, "mallEnv");
            return (Criteria) this;
        }

        public Criteria andMallEnvNotBetween(String value1, String value2) {
            addCriterion("mall_env not between", value1, value2, "mallEnv");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(String value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(String value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(String value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(String value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(String value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLike(String value) {
            addCriterion("longitude like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotLike(String value) {
            addCriterion("longitude not like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<String> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<String> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(String value1, String value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(String value1, String value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(String value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(String value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(String value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(String value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(String value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLike(String value) {
            addCriterion("latitude like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotLike(String value) {
            addCriterion("latitude not like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<String> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<String> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(String value1, String value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(String value1, String value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andIsUserDefinedCategoryIsNull() {
            addCriterion("is_user_defined_category is null");
            return (Criteria) this;
        }

        public Criteria andIsUserDefinedCategoryIsNotNull() {
            addCriterion("is_user_defined_category is not null");
            return (Criteria) this;
        }

        public Criteria andIsUserDefinedCategoryEqualTo(Integer value) {
            addCriterion("is_user_defined_category =", value, "isUserDefinedCategory");
            return (Criteria) this;
        }

        public Criteria andIsUserDefinedCategoryNotEqualTo(Integer value) {
            addCriterion("is_user_defined_category <>", value, "isUserDefinedCategory");
            return (Criteria) this;
        }

        public Criteria andIsUserDefinedCategoryGreaterThan(Integer value) {
            addCriterion("is_user_defined_category >", value, "isUserDefinedCategory");
            return (Criteria) this;
        }

        public Criteria andIsUserDefinedCategoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_user_defined_category >=", value, "isUserDefinedCategory");
            return (Criteria) this;
        }

        public Criteria andIsUserDefinedCategoryLessThan(Integer value) {
            addCriterion("is_user_defined_category <", value, "isUserDefinedCategory");
            return (Criteria) this;
        }

        public Criteria andIsUserDefinedCategoryLessThanOrEqualTo(Integer value) {
            addCriterion("is_user_defined_category <=", value, "isUserDefinedCategory");
            return (Criteria) this;
        }

        public Criteria andIsUserDefinedCategoryIn(List<Integer> values) {
            addCriterion("is_user_defined_category in", values, "isUserDefinedCategory");
            return (Criteria) this;
        }

        public Criteria andIsUserDefinedCategoryNotIn(List<Integer> values) {
            addCriterion("is_user_defined_category not in", values, "isUserDefinedCategory");
            return (Criteria) this;
        }

        public Criteria andIsUserDefinedCategoryBetween(Integer value1, Integer value2) {
            addCriterion("is_user_defined_category between", value1, value2, "isUserDefinedCategory");
            return (Criteria) this;
        }

        public Criteria andIsUserDefinedCategoryNotBetween(Integer value1, Integer value2) {
            addCriterion("is_user_defined_category not between", value1, value2, "isUserDefinedCategory");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ways_mall
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 14 15:11:25 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}