package com.example.demo.model;

import java.util.ArrayList;
import java.util.List;

public class WaysBuilderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public WaysBuilderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBuilderIdIsNull() {
            addCriterion("builder_id is null");
            return (Criteria) this;
        }

        public Criteria andBuilderIdIsNotNull() {
            addCriterion("builder_id is not null");
            return (Criteria) this;
        }

        public Criteria andBuilderIdEqualTo(Integer value) {
            addCriterion("builder_id =", value, "builderId");
            return (Criteria) this;
        }

        public Criteria andBuilderIdNotEqualTo(Integer value) {
            addCriterion("builder_id <>", value, "builderId");
            return (Criteria) this;
        }

        public Criteria andBuilderIdGreaterThan(Integer value) {
            addCriterion("builder_id >", value, "builderId");
            return (Criteria) this;
        }

        public Criteria andBuilderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("builder_id >=", value, "builderId");
            return (Criteria) this;
        }

        public Criteria andBuilderIdLessThan(Integer value) {
            addCriterion("builder_id <", value, "builderId");
            return (Criteria) this;
        }

        public Criteria andBuilderIdLessThanOrEqualTo(Integer value) {
            addCriterion("builder_id <=", value, "builderId");
            return (Criteria) this;
        }

        public Criteria andBuilderIdIn(List<Integer> values) {
            addCriterion("builder_id in", values, "builderId");
            return (Criteria) this;
        }

        public Criteria andBuilderIdNotIn(List<Integer> values) {
            addCriterion("builder_id not in", values, "builderId");
            return (Criteria) this;
        }

        public Criteria andBuilderIdBetween(Integer value1, Integer value2) {
            addCriterion("builder_id between", value1, value2, "builderId");
            return (Criteria) this;
        }

        public Criteria andBuilderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("builder_id not between", value1, value2, "builderId");
            return (Criteria) this;
        }

        public Criteria andBuilderNameIsNull() {
            addCriterion("builder_name is null");
            return (Criteria) this;
        }

        public Criteria andBuilderNameIsNotNull() {
            addCriterion("builder_name is not null");
            return (Criteria) this;
        }

        public Criteria andBuilderNameEqualTo(String value) {
            addCriterion("builder_name =", value, "builderName");
            return (Criteria) this;
        }

        public Criteria andBuilderNameNotEqualTo(String value) {
            addCriterion("builder_name <>", value, "builderName");
            return (Criteria) this;
        }

        public Criteria andBuilderNameGreaterThan(String value) {
            addCriterion("builder_name >", value, "builderName");
            return (Criteria) this;
        }

        public Criteria andBuilderNameGreaterThanOrEqualTo(String value) {
            addCriterion("builder_name >=", value, "builderName");
            return (Criteria) this;
        }

        public Criteria andBuilderNameLessThan(String value) {
            addCriterion("builder_name <", value, "builderName");
            return (Criteria) this;
        }

        public Criteria andBuilderNameLessThanOrEqualTo(String value) {
            addCriterion("builder_name <=", value, "builderName");
            return (Criteria) this;
        }

        public Criteria andBuilderNameLike(String value) {
            addCriterion("builder_name like", value, "builderName");
            return (Criteria) this;
        }

        public Criteria andBuilderNameNotLike(String value) {
            addCriterion("builder_name not like", value, "builderName");
            return (Criteria) this;
        }

        public Criteria andBuilderNameIn(List<String> values) {
            addCriterion("builder_name in", values, "builderName");
            return (Criteria) this;
        }

        public Criteria andBuilderNameNotIn(List<String> values) {
            addCriterion("builder_name not in", values, "builderName");
            return (Criteria) this;
        }

        public Criteria andBuilderNameBetween(String value1, String value2) {
            addCriterion("builder_name between", value1, value2, "builderName");
            return (Criteria) this;
        }

        public Criteria andBuilderNameNotBetween(String value1, String value2) {
            addCriterion("builder_name not between", value1, value2, "builderName");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andConstuctionIdIsNull() {
            addCriterion("constuction_id is null");
            return (Criteria) this;
        }

        public Criteria andConstuctionIdIsNotNull() {
            addCriterion("constuction_id is not null");
            return (Criteria) this;
        }

        public Criteria andConstuctionIdEqualTo(Integer value) {
            addCriterion("constuction_id =", value, "constuctionId");
            return (Criteria) this;
        }

        public Criteria andConstuctionIdNotEqualTo(Integer value) {
            addCriterion("constuction_id <>", value, "constuctionId");
            return (Criteria) this;
        }

        public Criteria andConstuctionIdGreaterThan(Integer value) {
            addCriterion("constuction_id >", value, "constuctionId");
            return (Criteria) this;
        }

        public Criteria andConstuctionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("constuction_id >=", value, "constuctionId");
            return (Criteria) this;
        }

        public Criteria andConstuctionIdLessThan(Integer value) {
            addCriterion("constuction_id <", value, "constuctionId");
            return (Criteria) this;
        }

        public Criteria andConstuctionIdLessThanOrEqualTo(Integer value) {
            addCriterion("constuction_id <=", value, "constuctionId");
            return (Criteria) this;
        }

        public Criteria andConstuctionIdIn(List<Integer> values) {
            addCriterion("constuction_id in", values, "constuctionId");
            return (Criteria) this;
        }

        public Criteria andConstuctionIdNotIn(List<Integer> values) {
            addCriterion("constuction_id not in", values, "constuctionId");
            return (Criteria) this;
        }

        public Criteria andConstuctionIdBetween(Integer value1, Integer value2) {
            addCriterion("constuction_id between", value1, value2, "constuctionId");
            return (Criteria) this;
        }

        public Criteria andConstuctionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("constuction_id not between", value1, value2, "constuctionId");
            return (Criteria) this;
        }

        public Criteria andBuildTypeIsNull() {
            addCriterion("build_type is null");
            return (Criteria) this;
        }

        public Criteria andBuildTypeIsNotNull() {
            addCriterion("build_type is not null");
            return (Criteria) this;
        }

        public Criteria andBuildTypeEqualTo(Integer value) {
            addCriterion("build_type =", value, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeNotEqualTo(Integer value) {
            addCriterion("build_type <>", value, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeGreaterThan(Integer value) {
            addCriterion("build_type >", value, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("build_type >=", value, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeLessThan(Integer value) {
            addCriterion("build_type <", value, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeLessThanOrEqualTo(Integer value) {
            addCriterion("build_type <=", value, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeIn(List<Integer> values) {
            addCriterion("build_type in", values, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeNotIn(List<Integer> values) {
            addCriterion("build_type not in", values, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeBetween(Integer value1, Integer value2) {
            addCriterion("build_type between", value1, value2, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("build_type not between", value1, value2, "buildType");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeIsNull() {
            addCriterion("identity_type is null");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeIsNotNull() {
            addCriterion("identity_type is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeEqualTo(Integer value) {
            addCriterion("identity_type =", value, "identityType");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeNotEqualTo(Integer value) {
            addCriterion("identity_type <>", value, "identityType");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeGreaterThan(Integer value) {
            addCriterion("identity_type >", value, "identityType");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("identity_type >=", value, "identityType");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeLessThan(Integer value) {
            addCriterion("identity_type <", value, "identityType");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeLessThanOrEqualTo(Integer value) {
            addCriterion("identity_type <=", value, "identityType");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeIn(List<Integer> values) {
            addCriterion("identity_type in", values, "identityType");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeNotIn(List<Integer> values) {
            addCriterion("identity_type not in", values, "identityType");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeBetween(Integer value1, Integer value2) {
            addCriterion("identity_type between", value1, value2, "identityType");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("identity_type not between", value1, value2, "identityType");
            return (Criteria) this;
        }

        public Criteria andIdentityCodeIsNull() {
            addCriterion("identity_code is null");
            return (Criteria) this;
        }

        public Criteria andIdentityCodeIsNotNull() {
            addCriterion("identity_code is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityCodeEqualTo(String value) {
            addCriterion("identity_code =", value, "identityCode");
            return (Criteria) this;
        }

        public Criteria andIdentityCodeNotEqualTo(String value) {
            addCriterion("identity_code <>", value, "identityCode");
            return (Criteria) this;
        }

        public Criteria andIdentityCodeGreaterThan(String value) {
            addCriterion("identity_code >", value, "identityCode");
            return (Criteria) this;
        }

        public Criteria andIdentityCodeGreaterThanOrEqualTo(String value) {
            addCriterion("identity_code >=", value, "identityCode");
            return (Criteria) this;
        }

        public Criteria andIdentityCodeLessThan(String value) {
            addCriterion("identity_code <", value, "identityCode");
            return (Criteria) this;
        }

        public Criteria andIdentityCodeLessThanOrEqualTo(String value) {
            addCriterion("identity_code <=", value, "identityCode");
            return (Criteria) this;
        }

        public Criteria andIdentityCodeLike(String value) {
            addCriterion("identity_code like", value, "identityCode");
            return (Criteria) this;
        }

        public Criteria andIdentityCodeNotLike(String value) {
            addCriterion("identity_code not like", value, "identityCode");
            return (Criteria) this;
        }

        public Criteria andIdentityCodeIn(List<String> values) {
            addCriterion("identity_code in", values, "identityCode");
            return (Criteria) this;
        }

        public Criteria andIdentityCodeNotIn(List<String> values) {
            addCriterion("identity_code not in", values, "identityCode");
            return (Criteria) this;
        }

        public Criteria andIdentityCodeBetween(String value1, String value2) {
            addCriterion("identity_code between", value1, value2, "identityCode");
            return (Criteria) this;
        }

        public Criteria andIdentityCodeNotBetween(String value1, String value2) {
            addCriterion("identity_code not between", value1, value2, "identityCode");
            return (Criteria) this;
        }

        public Criteria andIdStartTimeIsNull() {
            addCriterion("id_start_time is null");
            return (Criteria) this;
        }

        public Criteria andIdStartTimeIsNotNull() {
            addCriterion("id_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andIdStartTimeEqualTo(Integer value) {
            addCriterion("id_start_time =", value, "idStartTime");
            return (Criteria) this;
        }

        public Criteria andIdStartTimeNotEqualTo(Integer value) {
            addCriterion("id_start_time <>", value, "idStartTime");
            return (Criteria) this;
        }

        public Criteria andIdStartTimeGreaterThan(Integer value) {
            addCriterion("id_start_time >", value, "idStartTime");
            return (Criteria) this;
        }

        public Criteria andIdStartTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_start_time >=", value, "idStartTime");
            return (Criteria) this;
        }

        public Criteria andIdStartTimeLessThan(Integer value) {
            addCriterion("id_start_time <", value, "idStartTime");
            return (Criteria) this;
        }

        public Criteria andIdStartTimeLessThanOrEqualTo(Integer value) {
            addCriterion("id_start_time <=", value, "idStartTime");
            return (Criteria) this;
        }

        public Criteria andIdStartTimeIn(List<Integer> values) {
            addCriterion("id_start_time in", values, "idStartTime");
            return (Criteria) this;
        }

        public Criteria andIdStartTimeNotIn(List<Integer> values) {
            addCriterion("id_start_time not in", values, "idStartTime");
            return (Criteria) this;
        }

        public Criteria andIdStartTimeBetween(Integer value1, Integer value2) {
            addCriterion("id_start_time between", value1, value2, "idStartTime");
            return (Criteria) this;
        }

        public Criteria andIdStartTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("id_start_time not between", value1, value2, "idStartTime");
            return (Criteria) this;
        }

        public Criteria andIdEndTimeIsNull() {
            addCriterion("id_end_time is null");
            return (Criteria) this;
        }

        public Criteria andIdEndTimeIsNotNull() {
            addCriterion("id_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andIdEndTimeEqualTo(Integer value) {
            addCriterion("id_end_time =", value, "idEndTime");
            return (Criteria) this;
        }

        public Criteria andIdEndTimeNotEqualTo(Integer value) {
            addCriterion("id_end_time <>", value, "idEndTime");
            return (Criteria) this;
        }

        public Criteria andIdEndTimeGreaterThan(Integer value) {
            addCriterion("id_end_time >", value, "idEndTime");
            return (Criteria) this;
        }

        public Criteria andIdEndTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_end_time >=", value, "idEndTime");
            return (Criteria) this;
        }

        public Criteria andIdEndTimeLessThan(Integer value) {
            addCriterion("id_end_time <", value, "idEndTime");
            return (Criteria) this;
        }

        public Criteria andIdEndTimeLessThanOrEqualTo(Integer value) {
            addCriterion("id_end_time <=", value, "idEndTime");
            return (Criteria) this;
        }

        public Criteria andIdEndTimeIn(List<Integer> values) {
            addCriterion("id_end_time in", values, "idEndTime");
            return (Criteria) this;
        }

        public Criteria andIdEndTimeNotIn(List<Integer> values) {
            addCriterion("id_end_time not in", values, "idEndTime");
            return (Criteria) this;
        }

        public Criteria andIdEndTimeBetween(Integer value1, Integer value2) {
            addCriterion("id_end_time between", value1, value2, "idEndTime");
            return (Criteria) this;
        }

        public Criteria andIdEndTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("id_end_time not between", value1, value2, "idEndTime");
            return (Criteria) this;
        }

        public Criteria andIdImagesIsNull() {
            addCriterion("id_images is null");
            return (Criteria) this;
        }

        public Criteria andIdImagesIsNotNull() {
            addCriterion("id_images is not null");
            return (Criteria) this;
        }

        public Criteria andIdImagesEqualTo(Integer value) {
            addCriterion("id_images =", value, "idImages");
            return (Criteria) this;
        }

        public Criteria andIdImagesNotEqualTo(Integer value) {
            addCriterion("id_images <>", value, "idImages");
            return (Criteria) this;
        }

        public Criteria andIdImagesGreaterThan(Integer value) {
            addCriterion("id_images >", value, "idImages");
            return (Criteria) this;
        }

        public Criteria andIdImagesGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_images >=", value, "idImages");
            return (Criteria) this;
        }

        public Criteria andIdImagesLessThan(Integer value) {
            addCriterion("id_images <", value, "idImages");
            return (Criteria) this;
        }

        public Criteria andIdImagesLessThanOrEqualTo(Integer value) {
            addCriterion("id_images <=", value, "idImages");
            return (Criteria) this;
        }

        public Criteria andIdImagesIn(List<Integer> values) {
            addCriterion("id_images in", values, "idImages");
            return (Criteria) this;
        }

        public Criteria andIdImagesNotIn(List<Integer> values) {
            addCriterion("id_images not in", values, "idImages");
            return (Criteria) this;
        }

        public Criteria andIdImagesBetween(Integer value1, Integer value2) {
            addCriterion("id_images between", value1, value2, "idImages");
            return (Criteria) this;
        }

        public Criteria andIdImagesNotBetween(Integer value1, Integer value2) {
            addCriterion("id_images not between", value1, value2, "idImages");
            return (Criteria) this;
        }

        public Criteria andIsPrincipalIsNull() {
            addCriterion("is_principal is null");
            return (Criteria) this;
        }

        public Criteria andIsPrincipalIsNotNull() {
            addCriterion("is_principal is not null");
            return (Criteria) this;
        }

        public Criteria andIsPrincipalEqualTo(Short value) {
            addCriterion("is_principal =", value, "isPrincipal");
            return (Criteria) this;
        }

        public Criteria andIsPrincipalNotEqualTo(Short value) {
            addCriterion("is_principal <>", value, "isPrincipal");
            return (Criteria) this;
        }

        public Criteria andIsPrincipalGreaterThan(Short value) {
            addCriterion("is_principal >", value, "isPrincipal");
            return (Criteria) this;
        }

        public Criteria andIsPrincipalGreaterThanOrEqualTo(Short value) {
            addCriterion("is_principal >=", value, "isPrincipal");
            return (Criteria) this;
        }

        public Criteria andIsPrincipalLessThan(Short value) {
            addCriterion("is_principal <", value, "isPrincipal");
            return (Criteria) this;
        }

        public Criteria andIsPrincipalLessThanOrEqualTo(Short value) {
            addCriterion("is_principal <=", value, "isPrincipal");
            return (Criteria) this;
        }

        public Criteria andIsPrincipalIn(List<Short> values) {
            addCriterion("is_principal in", values, "isPrincipal");
            return (Criteria) this;
        }

        public Criteria andIsPrincipalNotIn(List<Short> values) {
            addCriterion("is_principal not in", values, "isPrincipal");
            return (Criteria) this;
        }

        public Criteria andIsPrincipalBetween(Short value1, Short value2) {
            addCriterion("is_principal between", value1, value2, "isPrincipal");
            return (Criteria) this;
        }

        public Criteria andIsPrincipalNotBetween(Short value1, Short value2) {
            addCriterion("is_principal not between", value1, value2, "isPrincipal");
            return (Criteria) this;
        }

        public Criteria andIsJoinIsNull() {
            addCriterion("is_join is null");
            return (Criteria) this;
        }

        public Criteria andIsJoinIsNotNull() {
            addCriterion("is_join is not null");
            return (Criteria) this;
        }

        public Criteria andIsJoinEqualTo(Short value) {
            addCriterion("is_join =", value, "isJoin");
            return (Criteria) this;
        }

        public Criteria andIsJoinNotEqualTo(Short value) {
            addCriterion("is_join <>", value, "isJoin");
            return (Criteria) this;
        }

        public Criteria andIsJoinGreaterThan(Short value) {
            addCriterion("is_join >", value, "isJoin");
            return (Criteria) this;
        }

        public Criteria andIsJoinGreaterThanOrEqualTo(Short value) {
            addCriterion("is_join >=", value, "isJoin");
            return (Criteria) this;
        }

        public Criteria andIsJoinLessThan(Short value) {
            addCriterion("is_join <", value, "isJoin");
            return (Criteria) this;
        }

        public Criteria andIsJoinLessThanOrEqualTo(Short value) {
            addCriterion("is_join <=", value, "isJoin");
            return (Criteria) this;
        }

        public Criteria andIsJoinIn(List<Short> values) {
            addCriterion("is_join in", values, "isJoin");
            return (Criteria) this;
        }

        public Criteria andIsJoinNotIn(List<Short> values) {
            addCriterion("is_join not in", values, "isJoin");
            return (Criteria) this;
        }

        public Criteria andIsJoinBetween(Short value1, Short value2) {
            addCriterion("is_join between", value1, value2, "isJoin");
            return (Criteria) this;
        }

        public Criteria andIsJoinNotBetween(Short value1, Short value2) {
            addCriterion("is_join not between", value1, value2, "isJoin");
            return (Criteria) this;
        }

        public Criteria andDecorationIdIsNull() {
            addCriterion("decoration_id is null");
            return (Criteria) this;
        }

        public Criteria andDecorationIdIsNotNull() {
            addCriterion("decoration_id is not null");
            return (Criteria) this;
        }

        public Criteria andDecorationIdEqualTo(Integer value) {
            addCriterion("decoration_id =", value, "decorationId");
            return (Criteria) this;
        }

        public Criteria andDecorationIdNotEqualTo(Integer value) {
            addCriterion("decoration_id <>", value, "decorationId");
            return (Criteria) this;
        }

        public Criteria andDecorationIdGreaterThan(Integer value) {
            addCriterion("decoration_id >", value, "decorationId");
            return (Criteria) this;
        }

        public Criteria andDecorationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("decoration_id >=", value, "decorationId");
            return (Criteria) this;
        }

        public Criteria andDecorationIdLessThan(Integer value) {
            addCriterion("decoration_id <", value, "decorationId");
            return (Criteria) this;
        }

        public Criteria andDecorationIdLessThanOrEqualTo(Integer value) {
            addCriterion("decoration_id <=", value, "decorationId");
            return (Criteria) this;
        }

        public Criteria andDecorationIdIn(List<Integer> values) {
            addCriterion("decoration_id in", values, "decorationId");
            return (Criteria) this;
        }

        public Criteria andDecorationIdNotIn(List<Integer> values) {
            addCriterion("decoration_id not in", values, "decorationId");
            return (Criteria) this;
        }

        public Criteria andDecorationIdBetween(Integer value1, Integer value2) {
            addCriterion("decoration_id between", value1, value2, "decorationId");
            return (Criteria) this;
        }

        public Criteria andDecorationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("decoration_id not between", value1, value2, "decorationId");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(Integer value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(Integer value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(Integer value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(Integer value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(Integer value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<Integer> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<Integer> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(Integer value1, Integer value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(Integer value1, Integer value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Integer value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Integer value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Integer> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Integer value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Integer value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Integer value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Integer value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Integer> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Integer> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ways_builder
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 14 15:47:07 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}