package com.example.demo.model;

import java.io.Serializable;

public class WaysMall implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.mall_id
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private Integer mallId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.mall_code
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String mallCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.mall_name
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String mallName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.mall_name_eng
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String mallNameEng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.mall_alias
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String mallAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.logo
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.is_use
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private Short isUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.create_by
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.create_time
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.update_by
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private Integer updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.update_time
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.place_code_separator
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String placeCodeSeparator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.address
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.status_of_micro_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String statusOfMicroMall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.wechat_public_account
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String wechatPublicAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.telphone
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.mall_type
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String mallType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.mall_env
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String mallEnv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.longitude
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.latitude
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.is_user_defined_category
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private Integer isUserDefinedCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_mall.customer_instructions
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private String customerInstructions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.mall_id
     *
     * @return the value of ways_mall.mall_id
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public Integer getMallId() {
        return mallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.mall_id
     *
     * @param mallId the value for ways_mall.mall_id
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setMallId(Integer mallId) {
        this.mallId = mallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.mall_code
     *
     * @return the value of ways_mall.mall_code
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getMallCode() {
        return mallCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.mall_code
     *
     * @param mallCode the value for ways_mall.mall_code
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setMallCode(String mallCode) {
        this.mallCode = mallCode == null ? null : mallCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.mall_name
     *
     * @return the value of ways_mall.mall_name
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getMallName() {
        return mallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.mall_name
     *
     * @param mallName the value for ways_mall.mall_name
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setMallName(String mallName) {
        this.mallName = mallName == null ? null : mallName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.mall_name_eng
     *
     * @return the value of ways_mall.mall_name_eng
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getMallNameEng() {
        return mallNameEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.mall_name_eng
     *
     * @param mallNameEng the value for ways_mall.mall_name_eng
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setMallNameEng(String mallNameEng) {
        this.mallNameEng = mallNameEng == null ? null : mallNameEng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.mall_alias
     *
     * @return the value of ways_mall.mall_alias
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getMallAlias() {
        return mallAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.mall_alias
     *
     * @param mallAlias the value for ways_mall.mall_alias
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setMallAlias(String mallAlias) {
        this.mallAlias = mallAlias == null ? null : mallAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.logo
     *
     * @return the value of ways_mall.logo
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.logo
     *
     * @param logo the value for ways_mall.logo
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.is_use
     *
     * @return the value of ways_mall.is_use
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public Short getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.is_use
     *
     * @param isUse the value for ways_mall.is_use
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setIsUse(Short isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.create_by
     *
     * @return the value of ways_mall.create_by
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.create_by
     *
     * @param createBy the value for ways_mall.create_by
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.create_time
     *
     * @return the value of ways_mall.create_time
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.create_time
     *
     * @param createTime the value for ways_mall.create_time
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.update_by
     *
     * @return the value of ways_mall.update_by
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.update_by
     *
     * @param updateBy the value for ways_mall.update_by
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.update_time
     *
     * @return the value of ways_mall.update_time
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.update_time
     *
     * @param updateTime the value for ways_mall.update_time
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.place_code_separator
     *
     * @return the value of ways_mall.place_code_separator
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getPlaceCodeSeparator() {
        return placeCodeSeparator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.place_code_separator
     *
     * @param placeCodeSeparator the value for ways_mall.place_code_separator
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setPlaceCodeSeparator(String placeCodeSeparator) {
        this.placeCodeSeparator = placeCodeSeparator == null ? null : placeCodeSeparator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.address
     *
     * @return the value of ways_mall.address
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.address
     *
     * @param address the value for ways_mall.address
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.status_of_micro_mall
     *
     * @return the value of ways_mall.status_of_micro_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getStatusOfMicroMall() {
        return statusOfMicroMall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.status_of_micro_mall
     *
     * @param statusOfMicroMall the value for ways_mall.status_of_micro_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setStatusOfMicroMall(String statusOfMicroMall) {
        this.statusOfMicroMall = statusOfMicroMall == null ? null : statusOfMicroMall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.wechat_public_account
     *
     * @return the value of ways_mall.wechat_public_account
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getWechatPublicAccount() {
        return wechatPublicAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.wechat_public_account
     *
     * @param wechatPublicAccount the value for ways_mall.wechat_public_account
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setWechatPublicAccount(String wechatPublicAccount) {
        this.wechatPublicAccount = wechatPublicAccount == null ? null : wechatPublicAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.telphone
     *
     * @return the value of ways_mall.telphone
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.telphone
     *
     * @param telphone the value for ways_mall.telphone
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.mall_type
     *
     * @return the value of ways_mall.mall_type
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getMallType() {
        return mallType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.mall_type
     *
     * @param mallType the value for ways_mall.mall_type
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setMallType(String mallType) {
        this.mallType = mallType == null ? null : mallType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.mall_env
     *
     * @return the value of ways_mall.mall_env
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getMallEnv() {
        return mallEnv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.mall_env
     *
     * @param mallEnv the value for ways_mall.mall_env
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setMallEnv(String mallEnv) {
        this.mallEnv = mallEnv == null ? null : mallEnv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.longitude
     *
     * @return the value of ways_mall.longitude
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.longitude
     *
     * @param longitude the value for ways_mall.longitude
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.latitude
     *
     * @return the value of ways_mall.latitude
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.latitude
     *
     * @param latitude the value for ways_mall.latitude
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.is_user_defined_category
     *
     * @return the value of ways_mall.is_user_defined_category
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public Integer getIsUserDefinedCategory() {
        return isUserDefinedCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.is_user_defined_category
     *
     * @param isUserDefinedCategory the value for ways_mall.is_user_defined_category
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setIsUserDefinedCategory(Integer isUserDefinedCategory) {
        this.isUserDefinedCategory = isUserDefinedCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_mall.customer_instructions
     *
     * @return the value of ways_mall.customer_instructions
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public String getCustomerInstructions() {
        return customerInstructions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_mall.customer_instructions
     *
     * @param customerInstructions the value for ways_mall.customer_instructions
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    public void setCustomerInstructions(String customerInstructions) {
        this.customerInstructions = customerInstructions == null ? null : customerInstructions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WaysMall other = (WaysMall) that;
        return (this.getMallId() == null ? other.getMallId() == null : this.getMallId().equals(other.getMallId()))
            && (this.getMallCode() == null ? other.getMallCode() == null : this.getMallCode().equals(other.getMallCode()))
            && (this.getMallName() == null ? other.getMallName() == null : this.getMallName().equals(other.getMallName()))
            && (this.getMallNameEng() == null ? other.getMallNameEng() == null : this.getMallNameEng().equals(other.getMallNameEng()))
            && (this.getMallAlias() == null ? other.getMallAlias() == null : this.getMallAlias().equals(other.getMallAlias()))
            && (this.getLogo() == null ? other.getLogo() == null : this.getLogo().equals(other.getLogo()))
            && (this.getIsUse() == null ? other.getIsUse() == null : this.getIsUse().equals(other.getIsUse()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getPlaceCodeSeparator() == null ? other.getPlaceCodeSeparator() == null : this.getPlaceCodeSeparator().equals(other.getPlaceCodeSeparator()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getStatusOfMicroMall() == null ? other.getStatusOfMicroMall() == null : this.getStatusOfMicroMall().equals(other.getStatusOfMicroMall()))
            && (this.getWechatPublicAccount() == null ? other.getWechatPublicAccount() == null : this.getWechatPublicAccount().equals(other.getWechatPublicAccount()))
            && (this.getTelphone() == null ? other.getTelphone() == null : this.getTelphone().equals(other.getTelphone()))
            && (this.getMallType() == null ? other.getMallType() == null : this.getMallType().equals(other.getMallType()))
            && (this.getMallEnv() == null ? other.getMallEnv() == null : this.getMallEnv().equals(other.getMallEnv()))
            && (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
            && (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
            && (this.getIsUserDefinedCategory() == null ? other.getIsUserDefinedCategory() == null : this.getIsUserDefinedCategory().equals(other.getIsUserDefinedCategory()))
            && (this.getCustomerInstructions() == null ? other.getCustomerInstructions() == null : this.getCustomerInstructions().equals(other.getCustomerInstructions()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMallId() == null) ? 0 : getMallId().hashCode());
        result = prime * result + ((getMallCode() == null) ? 0 : getMallCode().hashCode());
        result = prime * result + ((getMallName() == null) ? 0 : getMallName().hashCode());
        result = prime * result + ((getMallNameEng() == null) ? 0 : getMallNameEng().hashCode());
        result = prime * result + ((getMallAlias() == null) ? 0 : getMallAlias().hashCode());
        result = prime * result + ((getLogo() == null) ? 0 : getLogo().hashCode());
        result = prime * result + ((getIsUse() == null) ? 0 : getIsUse().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getPlaceCodeSeparator() == null) ? 0 : getPlaceCodeSeparator().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getStatusOfMicroMall() == null) ? 0 : getStatusOfMicroMall().hashCode());
        result = prime * result + ((getWechatPublicAccount() == null) ? 0 : getWechatPublicAccount().hashCode());
        result = prime * result + ((getTelphone() == null) ? 0 : getTelphone().hashCode());
        result = prime * result + ((getMallType() == null) ? 0 : getMallType().hashCode());
        result = prime * result + ((getMallEnv() == null) ? 0 : getMallEnv().hashCode());
        result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        result = prime * result + ((getIsUserDefinedCategory() == null) ? 0 : getIsUserDefinedCategory().hashCode());
        result = prime * result + ((getCustomerInstructions() == null) ? 0 : getCustomerInstructions().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mallId=").append(mallId);
        sb.append(", mallCode=").append(mallCode);
        sb.append(", mallName=").append(mallName);
        sb.append(", mallNameEng=").append(mallNameEng);
        sb.append(", mallAlias=").append(mallAlias);
        sb.append(", logo=").append(logo);
        sb.append(", isUse=").append(isUse);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", placeCodeSeparator=").append(placeCodeSeparator);
        sb.append(", address=").append(address);
        sb.append(", statusOfMicroMall=").append(statusOfMicroMall);
        sb.append(", wechatPublicAccount=").append(wechatPublicAccount);
        sb.append(", telphone=").append(telphone);
        sb.append(", mallType=").append(mallType);
        sb.append(", mallEnv=").append(mallEnv);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", isUserDefinedCategory=").append(isUserDefinedCategory);
        sb.append(", customerInstructions=").append(customerInstructions);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}