package com.example.demo.model;

import java.io.Serializable;

public class WaysBuilder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.builder_id
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private Integer builderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.builder_name
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private String builderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.mobile
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.constuction_id
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private Integer constuctionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.build_type
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private Integer buildType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.identity_type
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private Integer identityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.identity_code
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private String identityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.id_start_time
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private Integer idStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.id_end_time
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private Integer idEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.id_images
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private Integer idImages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.is_principal
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private Short isPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.is_join
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private Short isJoin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.decoration_id
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private Integer decorationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.create_by
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.create_time
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ways_builder.update_time
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.builder_id
     *
     * @return the value of ways_builder.builder_id
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Integer getBuilderId() {
        return builderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.builder_id
     *
     * @param builderId the value for ways_builder.builder_id
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setBuilderId(Integer builderId) {
        this.builderId = builderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.builder_name
     *
     * @return the value of ways_builder.builder_name
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public String getBuilderName() {
        return builderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.builder_name
     *
     * @param builderName the value for ways_builder.builder_name
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setBuilderName(String builderName) {
        this.builderName = builderName == null ? null : builderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.mobile
     *
     * @return the value of ways_builder.mobile
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.mobile
     *
     * @param mobile the value for ways_builder.mobile
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.constuction_id
     *
     * @return the value of ways_builder.constuction_id
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Integer getConstuctionId() {
        return constuctionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.constuction_id
     *
     * @param constuctionId the value for ways_builder.constuction_id
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setConstuctionId(Integer constuctionId) {
        this.constuctionId = constuctionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.build_type
     *
     * @return the value of ways_builder.build_type
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Integer getBuildType() {
        return buildType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.build_type
     *
     * @param buildType the value for ways_builder.build_type
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setBuildType(Integer buildType) {
        this.buildType = buildType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.identity_type
     *
     * @return the value of ways_builder.identity_type
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Integer getIdentityType() {
        return identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.identity_type
     *
     * @param identityType the value for ways_builder.identity_type
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setIdentityType(Integer identityType) {
        this.identityType = identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.identity_code
     *
     * @return the value of ways_builder.identity_code
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public String getIdentityCode() {
        return identityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.identity_code
     *
     * @param identityCode the value for ways_builder.identity_code
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setIdentityCode(String identityCode) {
        this.identityCode = identityCode == null ? null : identityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.id_start_time
     *
     * @return the value of ways_builder.id_start_time
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Integer getIdStartTime() {
        return idStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.id_start_time
     *
     * @param idStartTime the value for ways_builder.id_start_time
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setIdStartTime(Integer idStartTime) {
        this.idStartTime = idStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.id_end_time
     *
     * @return the value of ways_builder.id_end_time
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Integer getIdEndTime() {
        return idEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.id_end_time
     *
     * @param idEndTime the value for ways_builder.id_end_time
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setIdEndTime(Integer idEndTime) {
        this.idEndTime = idEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.id_images
     *
     * @return the value of ways_builder.id_images
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Integer getIdImages() {
        return idImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.id_images
     *
     * @param idImages the value for ways_builder.id_images
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setIdImages(Integer idImages) {
        this.idImages = idImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.is_principal
     *
     * @return the value of ways_builder.is_principal
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Short getIsPrincipal() {
        return isPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.is_principal
     *
     * @param isPrincipal the value for ways_builder.is_principal
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setIsPrincipal(Short isPrincipal) {
        this.isPrincipal = isPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.is_join
     *
     * @return the value of ways_builder.is_join
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Short getIsJoin() {
        return isJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.is_join
     *
     * @param isJoin the value for ways_builder.is_join
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setIsJoin(Short isJoin) {
        this.isJoin = isJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.decoration_id
     *
     * @return the value of ways_builder.decoration_id
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Integer getDecorationId() {
        return decorationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.decoration_id
     *
     * @param decorationId the value for ways_builder.decoration_id
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setDecorationId(Integer decorationId) {
        this.decorationId = decorationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.create_by
     *
     * @return the value of ways_builder.create_by
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.create_by
     *
     * @param createBy the value for ways_builder.create_by
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.create_time
     *
     * @return the value of ways_builder.create_time
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.create_time
     *
     * @param createTime the value for ways_builder.create_time
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ways_builder.update_time
     *
     * @return the value of ways_builder.update_time
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ways_builder.update_time
     *
     * @param updateTime the value for ways_builder.update_time
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WaysBuilder other = (WaysBuilder) that;
        return (this.getBuilderId() == null ? other.getBuilderId() == null : this.getBuilderId().equals(other.getBuilderId()))
            && (this.getBuilderName() == null ? other.getBuilderName() == null : this.getBuilderName().equals(other.getBuilderName()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getConstuctionId() == null ? other.getConstuctionId() == null : this.getConstuctionId().equals(other.getConstuctionId()))
            && (this.getBuildType() == null ? other.getBuildType() == null : this.getBuildType().equals(other.getBuildType()))
            && (this.getIdentityType() == null ? other.getIdentityType() == null : this.getIdentityType().equals(other.getIdentityType()))
            && (this.getIdentityCode() == null ? other.getIdentityCode() == null : this.getIdentityCode().equals(other.getIdentityCode()))
            && (this.getIdStartTime() == null ? other.getIdStartTime() == null : this.getIdStartTime().equals(other.getIdStartTime()))
            && (this.getIdEndTime() == null ? other.getIdEndTime() == null : this.getIdEndTime().equals(other.getIdEndTime()))
            && (this.getIdImages() == null ? other.getIdImages() == null : this.getIdImages().equals(other.getIdImages()))
            && (this.getIsPrincipal() == null ? other.getIsPrincipal() == null : this.getIsPrincipal().equals(other.getIsPrincipal()))
            && (this.getIsJoin() == null ? other.getIsJoin() == null : this.getIsJoin().equals(other.getIsJoin()))
            && (this.getDecorationId() == null ? other.getDecorationId() == null : this.getDecorationId().equals(other.getDecorationId()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBuilderId() == null) ? 0 : getBuilderId().hashCode());
        result = prime * result + ((getBuilderName() == null) ? 0 : getBuilderName().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getConstuctionId() == null) ? 0 : getConstuctionId().hashCode());
        result = prime * result + ((getBuildType() == null) ? 0 : getBuildType().hashCode());
        result = prime * result + ((getIdentityType() == null) ? 0 : getIdentityType().hashCode());
        result = prime * result + ((getIdentityCode() == null) ? 0 : getIdentityCode().hashCode());
        result = prime * result + ((getIdStartTime() == null) ? 0 : getIdStartTime().hashCode());
        result = prime * result + ((getIdEndTime() == null) ? 0 : getIdEndTime().hashCode());
        result = prime * result + ((getIdImages() == null) ? 0 : getIdImages().hashCode());
        result = prime * result + ((getIsPrincipal() == null) ? 0 : getIsPrincipal().hashCode());
        result = prime * result + ((getIsJoin() == null) ? 0 : getIsJoin().hashCode());
        result = prime * result + ((getDecorationId() == null) ? 0 : getDecorationId().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", builderId=").append(builderId);
        sb.append(", builderName=").append(builderName);
        sb.append(", mobile=").append(mobile);
        sb.append(", constuctionId=").append(constuctionId);
        sb.append(", buildType=").append(buildType);
        sb.append(", identityType=").append(identityType);
        sb.append(", identityCode=").append(identityCode);
        sb.append(", idStartTime=").append(idStartTime);
        sb.append(", idEndTime=").append(idEndTime);
        sb.append(", idImages=").append(idImages);
        sb.append(", isPrincipal=").append(isPrincipal);
        sb.append(", isJoin=").append(isJoin);
        sb.append(", decorationId=").append(decorationId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}