package com.example.demo.dal;

import com.example.demo.model.StudyCallRecord;
import com.example.demo.model.StudyCallRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudyCallRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    int countByExample(StudyCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    int deleteByExample(StudyCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    int deleteByPrimaryKey(Integer callRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    int insert(StudyCallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    int insertSelective(StudyCallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    List<StudyCallRecord> selectByExample(StudyCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    StudyCallRecord selectByPrimaryKey(Integer callRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") StudyCallRecord record, @Param("example") StudyCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    int updateByExample(@Param("record") StudyCallRecord record, @Param("example") StudyCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    int updateByPrimaryKeySelective(StudyCallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_call_record
     *
     * @mbggenerated Wed Apr 15 22:59:40 CST 2020
     */
    int updateByPrimaryKey(StudyCallRecord record);
}