package com.example.demo.dal;

import com.example.demo.model.WaysMall;
import com.example.demo.model.WaysMallExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WaysMallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    int countByExample(WaysMallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    int deleteByExample(WaysMallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    int deleteByPrimaryKey(Integer mallId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    int insert(WaysMall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    int insertSelective(WaysMall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    List<WaysMall> selectByExampleWithBLOBs(WaysMallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    List<WaysMall> selectByExample(WaysMallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    WaysMall selectByPrimaryKey(Integer mallId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") WaysMall record, @Param("example") WaysMallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") WaysMall record, @Param("example") WaysMallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    int updateByExample(@Param("record") WaysMall record, @Param("example") WaysMallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    int updateByPrimaryKeySelective(WaysMall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(WaysMall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_mall
     *
     * @mbggenerated Tue Apr 14 15:11:25 CST 2020
     */
    int updateByPrimaryKey(WaysMall record);

    List<WaysMall> selectAll();
}