package com.example.demo.dal;

import com.example.demo.model.WaysBuilder;
import com.example.demo.model.WaysBuilderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WaysBuilderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    int countByExample(WaysBuilderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    int deleteByExample(WaysBuilderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    int deleteByPrimaryKey(Integer builderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    int insert(WaysBuilder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    int insertSelective(WaysBuilder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    List<WaysBuilder> selectByExample(WaysBuilderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    WaysBuilder selectByPrimaryKey(Integer builderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") WaysBuilder record, @Param("example") WaysBuilderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    int updateByExample(@Param("record") WaysBuilder record, @Param("example") WaysBuilderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    int updateByPrimaryKeySelective(WaysBuilder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ways_builder
     *
     * @mbggenerated Tue Apr 14 15:47:07 CST 2020
     */
    int updateByPrimaryKey(WaysBuilder record);
}