server:
  port: 8079
  name: ck-first-service

endpoints:
  restart:
    enabled: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.expample.demo.model

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

spring:
  redis:
    database: 0
    host: 106.14.252.88
    port: 6380
    password: 123456

nacos:
  config:
    server-addr: 47.94.13.132:8848
  discovery:
    server-addr: 47.94.13.132:8848

threadPool:
  corePoolSize: 2
  maxPoolSize: 4
  queueCapacity: 50
  keepAliveSeconds: 180
  waitForTasksToCompleteOnShutdown: true
  client:
    config:
      default:
        connect-timeout: 100000
        read-timeout: 200000


