server:
  port: 8088
info:
  component: my-first-spring
endpoints:
  restart:
    enabled: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.expample.demo.model

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

spring:
  redis:
    database: 0
    host: 47.94.13.132
    port: 6379

